version: '3.8'

services:
  # 1. Veritabanı: TimescaleDB (Postgres tabanlı)
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: v2_timescaledb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trading_v2
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data # Veriler kaybolmasın diye
    networks:
      - trading-net

  # 3. İleride buraya kendi Go uygulamamızı da ekleyeceğiz (Dockerfile ile)

networks:
  trading-net:
    driver: bridge